'use client'
import{useState}from'react'
export default function Calculator(){
 const[v,setV]=useState(''),[mode,setMode]=useState('bill'),[cat,setCat]=useState('Domestic'),[balance,setBalance]=useState(''),[requested,setRequested]=useState(''),[r,setR]=useState<any>(null),[busy,setBusy]=useState(false)
 const run=async()=>{setBusy(true);try{const x=await fetch('/api/admin/calculator',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({input:v,mode,category:cat,balanceAvailableKw:balance,requestedKw:requested})});setR(await x.json())}finally{setBusy(false)}}
 const n=(x:any)=>x==null?'—':Number(x).toLocaleString('en-IN')
 return <main className="min-h-dvh bg-[#03132f] p-4"><div className="mx-auto max-w-3xl rounded-3xl bg-white p-5"><h1 className="text-2xl font-black text-[#1260a4]">Advanced Solar Calculator</h1><p className="mt-1 text-sm text-slate-500">Admin-only calculation. Uses the same core calculator without public lead/rate-limit side effects.</p>
 <div className="mt-5 grid gap-3 sm:grid-cols-2"><select value={mode} onChange={e=>setMode(e.target.value)} className="rounded-xl border p-3"><option value="bill">Monthly bill ₹</option><option value="units">Monthly units kWh</option></select><select value={cat} onChange={e=>setCat(e.target.value)} className="rounded-xl border p-3"><option>Domestic</option><option>Commercial</option></select><input type="number" min="1" value={v} onChange={e=>setV(e.target.value)} placeholder={mode==='bill'?'Monthly bill':'Monthly units'} className="rounded-xl border p-3"/><input type="number" min="0" value={balance} onChange={e=>setBalance(e.target.value)} placeholder="Transformer balance kW (optional)" className="rounded-xl border p-3"/><input type="number" min="0" value={requested} onChange={e=>setRequested(e.target.value)} placeholder="Requested plant kW (optional)" className="rounded-xl border p-3"/></div>
 <button disabled={busy} onClick={run} className="mt-3 w-full rounded-2xl bg-[#1260a4] p-3 font-bold text-white disabled:opacity-50">{busy?'CALCULATING...':'CALCULATE'}</button>
 {r?.result&&<div className="mt-5 grid gap-3 sm:grid-cols-2"><Card t="Recommended system" v={n(r.result.kw)+' kW'}/><Card t="Estimated monthly savings" v={'₹'+n(r.result.estimatedMonthlySavings)}/><Card t="Estimated annual savings" v={'₹'+n(r.result.estimatedAnnualSavings)}/><Card t="Payback" v={r.result.paybackYears==null?'—':r.result.paybackYears+' years'}/><Card t="System cost" v={'₹'+n(r.result.cost)}/><Card t="Subsidy" v={'₹'+n(r.result.subsidy)}/><Card t="Net system cost" v={'₹'+n(r.result.netSystemCost)}/><Card t="Estimated EMI" v={'₹'+n(r.result.loanAssumption?.estimatedEmi)}/>{r.result.feasibility&&<Card t="KSEB feasibility" v={r.result.feasibility.status+' · '+n(r.result.feasibility.remainingAfterInstallationKw)+' kW remaining'}/>}</div>}
 {r?.message&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{r.message}</p>}</div></main>
}
function Card({t,v}:{t:string;v:string}){return <div className="rounded-2xl border bg-slate-50 p-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">{t}</p><p className="mt-1 text-lg font-black text-slate-900">{v}</p></div>}
