import {NextResponse} from 'next/server'
import {ensureLeadTable,getSql} from '@/lib/db'
import {requireAdmin} from '@/lib/adminAuth'
import {auditEvent} from '@/lib/adminAudit'
const u=(e:unknown)=>e instanceof Error&&e.message==='UNAUTHORIZED'

export async function GET(req:Request){try{await requireAdmin();await ensureLeadTable();const params=new URL(req.url).searchParams;const id=params.get('leadId');const page=Math.max(1,Number(params.get('page')||'1')||1);const pageSize=Math.min(100,Math.max(1,Number(params.get('pageSize')||'50')||50));const offset=(page-1)*pageSize;const sql=getSql();const r=(id?await sql.query('SELECT * FROM lead_payments WHERE lead_id=$1 ORDER BY paid_at DESC LIMIT $2 OFFSET $3',[id,pageSize,offset]):await sql.query('SELECT * FROM lead_payments ORDER BY paid_at DESC LIMIT $1 OFFSET $2',[pageSize,offset])) as Record<string,any>[];const t=(id?await sql.query('SELECT COUNT(*)::int AS total FROM lead_payments WHERE lead_id=$1',[id]):await sql.query('SELECT COUNT(*)::int AS total FROM lead_payments')) as Record<string,any>[];const total=Number(t[0]?.total||0);return NextResponse.json({success:true,payments:r,page,pageSize,total,hasMore:offset+r.length<total})}catch(e){return NextResponse.json({success:false,message:u(e)?'Unauthorized':'Failed'},{status:u(e)?401:500})}}
export async function POST(req:Request){try{const a=await requireAdmin();await ensureLeadTable();const b=await req.json();const leadId=String(b.leadId??'').trim();const amount=Number(b.amount);if(!leadId||!Number.isFinite(amount)||amount<=0)return NextResponse.json({success:false,message:'Valid leadId and amount required'},{status:400});const leadExists=await getSql().query('SELECT 1 FROM leads WHERE lead_id=$1 LIMIT 1',[leadId]);if(!(leadExists as unknown as unknown[]).length)return NextResponse.json({success:false,message:'Lead not found'},{status:404});const r=(await getSql().query('INSERT INTO lead_payments (lead_id,amount,paid_at,method,note,recorded_by_name) VALUES ($1,$2,COALESCE($3,NOW()),$4,$5,$6) RETURNING *',[leadId,amount,b.paidAt??null,b.method??null,b.note??null,a.name])) as Record<string,any>[];await auditEvent(leadId,'payment','₹'+amount+' recorded by '+a.name,a);return NextResponse.json({success:true,payment:r[0]})}catch(e){return NextResponse.json({success:false,message:u(e)?'Unauthorized':'Failed'},{status:u(e)?401:500})}}
export async function PATCH(req:Request){try{const a=await requireAdmin();await ensureLeadTable();const b=await req.json();const id=Number(b.id);const amount=Number(b.amount);if(!id||!Number.isFinite(amount)||amount<0)return NextResponse.json({success:false,message:'Valid payment id and amount required'},{status:400});const r=(await getSql().query('UPDATE lead_payments SET amount=$1 WHERE id=$2 RETURNING *',[amount,id])) as Record<string,any>[];if(!r.length)return NextResponse.json({success:false,message:'Payment not found'},{status:404});await auditEvent(String(r[0].lead_id),'payment','₹'+amount+' updated by '+a.name,a);return NextResponse.json({success:true,payment:r[0]})}catch(e){return NextResponse.json({success:false,message:u(e)?'Unauthorized':'Failed'},{status:u(e)?401:500})}}
export async function DELETE(req:Request){try{const a=await requireAdmin();await ensureLeadTable();const b=await req.json();const id=Number(b.id);if(!id||!String(b.reason??'').trim())return NextResponse.json({success:false,message:'Payment id and deletion reason required'},{status:400});const r=(await getSql().query('DELETE FROM lead_payments WHERE id=$1 RETURNING *',[id])) as Record<string,any>[];if(!r.length)return NextResponse.json({success:false,message:'Not found'},{status:404});await auditEvent(String(r[0].lead_id),'payment','payment '+id+' deleted: '+String(b.reason)+' by '+a.name,a);return NextResponse.json({success:true})}catch(e){return NextResponse.json({success:false,message:u(e)?'Unauthorized':'Failed'},{status:u(e)?401:500})}}