'use client'

import { useState } from 'react'

const CDN='https://cdn.jsdelivr.net/npm/pdf-lib@1.17.1/dist/pdf-lib.min.js'
function loadPdfLib():Promise<any>{if((window as any).PDFLib)return Promise.resolve((window as any).PDFLib);return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=CDN;s.onload=()=>resolve((window as any).PDFLib);s.onerror=()=>reject(new Error('Unable to load PDF library'));document.head.appendChild(s)})}
type Field={name:string;type:string;value:string}
type Overlay={name:string;page:number;x:number;y:number;size:number;value:string}
export default function FormsFilling(){
 const[file,setFile]=useState<File|null>(null),[fields,setFields]=useState<Field[]>([]),[overlays,setOverlays]=useState<Overlay[]>([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false)
 const inspect=async(f:File)=>{setFile(f);setMsg('');try{const P=await loadPdfLib(),d=await P.PDFDocument.load(new Uint8Array(await f.arrayBuffer()));const fs=d.getForm().getFields().map((x:any)=>({name:x.getName(),type:x.constructor.name,value:''}));setFields(fs);setMsg(fs.length?fs.length+' fillable PDF field(s) detected.':'No AcroForm fields detected. Add coordinate overlays for scanned/non-fillable forms.')}catch(e){setMsg(e instanceof Error?e.message:'Invalid PDF')}}
 const fill=async()=>{if(!file)return;setBusy(true);try{const P=await loadPdfLib(),d=await P.PDFDocument.load(new Uint8Array(await file.arrayBuffer())),form=d.getForm();for(const f of fields){if(!f.value)continue;try{const field=form.getField(f.name) as any;if(typeof field.setText==='function')field.setText(f.value);else if(typeof field.check==='function'&&f.value==='true')field.check();else if(typeof field.select==='function')field.select(f.value)}catch{}}
 const font=await d.embedFont(P.StandardFonts.Helvetica),black=P.rgb(0.03,0.05,0.1);for(const o of overlays){const p=d.getPages()[o.page-1];if(p)p.drawText(o.value||'',{x:o.x,y:o.y,size:o.size||9,font,color:black})}
 const bytes=await d.save(),blob=new Blob([bytes],{type:'application/pdf'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='DiSun_Filled_Form.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMsg('Filled PDF generated.')}catch(e){setMsg(e instanceof Error?e.message:'Unable to fill PDF')}finally{setBusy(false)}}
 const add=()=>setOverlays(x=>[...x,{name:'Field '+(x.length+1),page:1,x:50,y:750,size:9,value:''}])
 return <main className="min-h-dvh bg-slate-100 p-4"><div className="mx-auto max-w-5xl space-y-4"><header className="rounded-3xl bg-[#03132f] p-5 text-white"><p className="text-xs font-bold uppercase tracking-widest text-sky-300">DiSun Admin</p><h1 className="mt-1 text-2xl font-black">Forms Filling</h1><p className="mt-1 text-sm text-slate-300">Fill AcroForm PDFs automatically or place text on scanned/non-fillable PDFs.</p></header>
 <section className="rounded-3xl bg-white p-5 shadow-sm"><input type="file" accept="application/pdf" onChange={e=>e.target.files?.[0]&&inspect(e.target.files[0])} className="w-full text-sm"/>{msg&&<p className="mt-3 rounded-xl bg-slate-50 p-3 text-sm font-bold text-slate-600">{msg}</p>}</section>
 {fields.length>0&&<section className="rounded-3xl bg-white p-5 shadow-sm"><h2 className="font-black">Detected fields</h2><div className="mt-3 grid gap-2 sm:grid-cols-2">{fields.map((f,i)=><label key={f.name} className="block"><span className="text-xs font-bold text-slate-500">{f.name} · {f.type}</span><input value={f.value} onChange={e=>setFields(x=>x.map((z,j)=>j===i?{...z,value:e.target.value}:z))} className="mt-1 w-full rounded-xl border p-3 text-sm"/></label>)}</div></section>}
 <section className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-black">Coordinate overlays</h2><button onClick={add} className="rounded-xl bg-slate-100 px-3 py-2 text-xs font-bold">+ Add field</button></div><p className="mt-1 text-xs text-slate-500">Coordinates use PDF points from the bottom-left.</p><div className="mt-3 space-y-2">{overlays.map((o,i)=><div key={i} className="grid gap-2 sm:grid-cols-6"><input value={o.name} onChange={e=>setOverlays(x=>x.map((z,j)=>j===i?{...z,name:e.target.value}:z))} className="rounded-xl border p-2 text-sm sm:col-span-2" placeholder="Field name"/><input type="number" value={o.page} onChange={e=>setOverlays(x=>x.map((z,j)=>j===i?{...z,page:Number(e.target.value)}:z))} className="rounded-xl border p-2 text-sm" placeholder="Page"/><input type="number" value={o.x} onChange={e=>setOverlays(x=>x.map((z,j)=>j===i?{...z,x:Number(e.target.value)}:z))} className="rounded-xl border p-2 text-sm" placeholder="X"/><input type="number" value={o.y} onChange={e=>setOverlays(x=>x.map((z,j)=>j===i?{...z,y:Number(e.target.value)}:z))} className="rounded-xl border p-2 text-sm" placeholder="Y"/><input type="number" value={o.size} onChange={e=>setOverlays(x=>x.map((z,j)=>j===i?{...z,size:Number(e.target.value)}:z))} className="rounded-xl border p-2 text-sm" placeholder="Size"/><input value={o.value} onChange={e=>setOverlays(x=>x.map((z,j)=>j===i?{...z,value:e.target.value}:z))} className="rounded-xl border p-2 text-sm sm:col-span-2" placeholder="Value"/></div>)}</div></section>
 <button disabled={!file||busy} onClick={fill} className="rounded-2xl bg-sky-600 px-6 py-3 font-black text-white disabled:opacity-40">{busy?'PROCESSING...':'FILL & DOWNLOAD PDF'}</button></div></main>
}